# Generated by Django 4.2.6 on 2023-11-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_pw', models.CharField(max_length=4, verbose_name='비밀번호')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='주문날짜')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='files/')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprint.upload')),
            ],
        ),
    ]
