# Generated by Django 4.2.6 on 2023-11-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprint', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_pw',
            field=models.CharField(max_length=16, verbose_name='비밀번호'),
        ),
    ]
